[window]
padding.x = 25
padding.y = 25

decorations = "Buttonless"

opacity = 0.95
blur = false

option_as_alt = "Both"

[font]
normal.family = "JetBrains Mono"
size = 18

[cursor]
blink_interval = 500
blink_timeout = 0
unfocused_hollow = false
    [cursor.style]
    shape = "Block"
    blinking = "Always"

[mouse]
hide_when_typing = true

[terminal]

[terminal.shell]
program = "/run/current-system/sw/bin/bash"
args = ["-l"]

[general]
import = [ "~/.config/alacritty/themes/solarized_light.toml"]
