import = [ "~/.config/alacritty/themes/solarized_light.toml"]

[window]
padding.x = 15
padding.y = 25

decorations = "Buttonless"

opacity = 1.0
blur = false

option_as_alt = "Both"

[font]
#normal.family = "Monaco"
normal.family = "firaCode Nerd Font Mono"
size = 16
