import = [ "~/.config/alacritty/themes/solarized_light.toml"]

[window]
padding.x = 15
padding.y = 25

decorations = "Buttonless"

opacity = 1.0
blur = false

option_as_alt = "Both"

[font]
#normal.family = "Monaco"
#normal.family = "firaCode Nerd Font Mono"
normal.family = "Hack Nerd Font Mono"
size = 18

[cursor]
blink_interval = 500
blink_timeout = 0
unfocused_hollow = false
    [cursor.style]
    shape = "Block"
    blinking = "Always"

[mouse]
hide_when_typing = true
