#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'blue'
    template = '{{ .Path }} '

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'p:grey'
    background = 'transparent'
    template = '{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true
  [[blocks.segments]]
    type = 'aws'
    foreground = "black"
    background = "lightYellow"
    template = " AWS {{.Profile}}{{if .Region}}@{{.Region}}{{end}} "


[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'lightRed'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 1

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}lightCyan{{end}}",
      "{{if eq .Code 0}}cyan{{end}}",
    ]
    background = 'transparent'
    template = '❯_'

# it is not working in bash
[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}lightCyan{{end}}",
    "{{if eq .Code 0}}cyan{{end}}",
  ]
  background = 'transparent'
  template = '❯_'

[secondary_prompt]
  foreground = 'cyan'
  background = 'transparent'
  template = '❯❯ '
