# Colors (Solarized Dark)
[colors.cursor]
text = '#ffffff'
cursor = '#586e75'

[colors.primary]
background = '#002b36'
foreground = '#93a1a1'

[colors.normal]
black   = '#002b36'
red     = '#dc322f'
green   = '#859900'
yellow  = '#b58900'
blue    = '#268bd2'
magenta = '#6c71c4'
cyan    = '#2aa198'
white   = '#93a1a1'

[colors.bright]
black   = '#657b83'
red     = '#b52828'
green   = '#677300'
yellow  = '#8f6400'
blue    = '#2272ab'
magenta = '#545f9e'
cyan    = '#d33682'
white   = '#fdf6e3'
