#!/usr/bin/env bash

if [ ${1:-0} -gt "7" ]; then echo "up to 7 only"; exit 1; fi

# Path to image file
path="$HOME/Dropbox/bing_images/$(date --date="today-${1:-0} days" +bing-%Y-%m-%d.jpg)"

if [ ${2:-""} == "force" ]; then rm ${path}; fi

if [ ! -e "$path" ]; then
    urlpath=$( \
    curl -s "https://www.bing.com/HPImageArchive.aspx?format=rss&idx=${1}&n=1" \
    | xmllint --xpath "/rss/channel/item/link/text()" - \
    | sed 's/1366x768/1920x1080/g' \
    )
    curl -s "https://www.bing.com$urlpath" -o "${path}"
    feh --bg-fill --no-fehbg ${path}
else
    feh --bg-fill --no-fehbg ${path}
fi

