#!/usr/bin/env bash

printf "\n"
for fgbg in 38 48; do
    for color in {1..15} 0 ; do
        printf "\e[${fgbg};5;%sm  %3s  \e[0;49;30m" $color $color
        if [ $((($color + 1 ) % 8)) == 1 ]; then
            printf "\n"
        fi
    done
    printf "\n"
done
