#!/usr/bin/env bash

echo "Updating all dockers images"
echo
docker images --digests | ggrep -vP "nimasaed*|\<none\>" | tail -n+2 | awk '{print $1":"$2}' | xargs -L1 docker pull
echo

# clean up
docker image prune --force
