#!/usr/bin/env bash
set -o nounset # Treat unset variables as an error

filename=$(echo $1 | grep -o ^[a-zA-Z0-9_]*)
# use pandoc and beamer

#pandoc "$1" -t beamer -o "$PWD/$filename.pdf" --filter mermaid-filter

pandoc "$1" -t beamer -o "$PWD/$filename.pdf" --pdf-engine=/Library/TeX/texbin/pdflatex --filter mermaid-filter

echo "$PWD/${filename}.pdf"
exit 0
