#!/usr/bin/env bash

wireless1="wlp2s0"
#wireless2=$(ip link | grep -Po "wlp0s[a-z0-9]{1,}")

conf_path='/home/nima/Dropbox/Arch Linux/wifi-configs/'

wpa_config="wpa_supplicant.conf"

wpa_supplicant -D nl80211 -i $wireless1 -c "${conf_path}${wpa_config}"
