#!/usr/bin/env bash

wireless=$(ip link  | grep -Po 'w[\w\d]{1,}')

#sudo systemctl start wpa_supplicant.service
wpa_supplicant -D nl80211 -i $wireless -c /home/nima/Dropbox/Arch\ Linux/wpa_supplicant.conf
