#!/usr/bin/env bash

ignore_list=""
curl -s "https://archlinux.org/mirrorlist/?country=${1:-NL}&protocol=${2:-https}&ip_version=${3:-4}" | cut -c2- > mirrors
rankmirrors -n ${4:-1} -v mirrors | tee  mirrorlist
rm mirrors
sudo mv mirrorlist /etc/pacman.d/mirrorlist
yay -Syyu --ignore $ignore_list
