#!/usr/bin/env bash

mode="--auto"
scale_value="1.50x1.50"
mainScreen=$(xrandr | grep -w primary | awk '{print $1}')
SecondScreen=$(xrandr | grep -w connected | grep -v primary | awk {'print $1'})

# main screen only, if the external monitor is connected
if [ "$1" == "off" ] && [ "${SecondScreen}" ]; then
    xrandr --output ${SecondScreen} --off --output ${mainScreen} ${mode} --scale ${scale_value}
# main screen only, if there are no external monitor connected
elif [ "$1" == "off" ]; then
    xrandr --output ${mainScreen} ${mode} --scale ${scale_value}
# Mirror
elif [ "$1" == "m" ] && [ "${SecondScreen}" ]; then
    xrandr --output ${SecondScreen} ${mode}\
           --output ${mainScreen} ${mode} --same-as ${SecondScreen}\
           --scale `echo "3840/1920" | bc -l`x`echo "2160/1080" | bc -l`
# Extended
elif [ "$1" == "e" ] && [ "${SecondScreen}" ] ; then
    xrandr --output ${SecondScreen} ${mode}\
           --output  ${mainScreen} ${mode} --below ${SecondScreen}\
           --scale ${scale_value}
# External monitor only
elif [ "$1" == "s" ] && [ "${SecondScreen}" ] ; then
    xrandr --output ${mainScreen} --off --output ${SecondScreen} ${mode}
else
    echo "No second screen is connected"
fi

i3 restart
bing-background
