#!/usr/bin/env bash

if [ "$(uname)" == "Darwin" ];
then
    sed="/opt/homebrew/opt/gnu-sed/libexec/gnubin/sed"
    themeFile="/Users/nima/.config/alacritty/alacritty.toml"
    case $1 in
        l)
            sed -i 's/dark/light/g' $themeFile
            ;;
        d)
            sed -i 's/light/dark/g' $themeFile
            ;;
        t)
            if [ "$(head -1 $themeFile | grep -Eo "_(d|l)" | grep -Eo "[a-zA-Z]")" == "d" ];
            then
                sed -i 's/dark/light/g' $themeFile
            else
                sed -i 's/light/dark/g' $themeFile
            fi
            ;;
    esac
else
    terminal=st
    browser=firefox

    currentTheme=$(cat ~/.Xresources | grep theme | cut -d' ' -f3)
    theme=""

    case $currentTheme in

        light)
            theme=dark
            ;;
        dark)
            theme=light
            ;;
    esac

    newcolor=""
    oldcolor=""
    for i in {0..9} {A..I}; do
        newcolor="${newcolor}\n$(cat ~/.colors/solarized-${theme} | grep -w "#define base0${i}")"
        oldcolor="${oldcolor}\n$(cat ~/.Xresources | grep -w "#define base0${i}")"
    done

    sed "s/${currentTheme}/${theme}/" <~/.Xresources >~/.Xresources.tmp
    sed ':a;N;$!ba;s/'"${oldcolor}"'/'"${newcolor}"'/' <~/.Xresources.tmp >~/.Xresources
    rm .Xresources.tmp
    xrdb -merge ~/.Xresources
    i3-msg reload > /dev/null
    hsetroot -solid "$(xrdb -query | grep -w color8 | cut -f2)"

    # If there is a terminal open
    terminal_psid=$(ps -e | grep -w ${terminal} | grep -oP '[\d]{3,}')
    if [ ! -z ${terminal_psid} ]; then
        killall ${terminal}
        export TMUX=""
        ${terminal} -e bash --rcfile ~/.bash_profile &
    fi

    bing-background
fi

exit 0
