#!/usr/bin/env bash
set -o nounset # Treat unset variables as an error

#arg=${1:-""}
#
#if [ "$arg" == "" ]; then
#    vim  "$HOME/Dropbox/Notes/.old_Notes/Inbox/$(date "+%Y-Week-%V-todo.md")";
#elif [ "$arg" == "-w" ]; then
#    filename=$(date --date="next monday - $(( 1 + $2 )) week" "+%Y-Week-%V-todo.md")
#    if [ "$2" = "" ]; then
#        filename=$(date "+%Y-Week-%V-todo.md")
#    fi
#    vim  "$HOME/Dropbox/Notes/.old_Notes/Inbox/$filename";
#else
#    echo "error"
#fi


vim "$HOME/Dropbox/Notes/todo.md"
