#!/bin/env bash

arg=$1

if [ "$arg" == "" ]; then
    vim  "/home/nima/Dropbox/Notes/Inbox/$(date '+%Y-%m-%d-todo.md')";
elif [ "$arg" == "-d" ]; then
    filename=$(date --date="today-$2 days" "+%Y-%m-%d-todo.md")
    if [ "$2" = "" ]; then
        filename=$(date --date="today-0 days" "+%Y-%m-%d-todo.md")
    fi
    vim  "/home/nima/Dropbox/Notes/Inbox/$filename";
else
    echo "error"
fi
