#!/usr/bin/env bash
activeDevice=$(pactl info | grep Default\ Sink | awk '{print $3}')
Mute=$(pactl list sinks | grep $activeDevice -A 7 | grep Mute | awk '{print $2}')
if [ "$Mute" == "no" ]; then
    icon="";
    vol=$(pactl list sinks | grep $activeDevice -A 7 | grep -m 1 -oE '[0-9]{1,}%' | grep -m 1 '');
else
    vol=$(pactl list sinks | grep $activeDevice -A 7 | grep -m 1 -oE '[0-9]{1,}%' | grep -m 1 '');
    icon="";
fi
echo -n "$vol $icon";
