#!/usr/bin/env bash
tmux a -t Main || \
tmux new -s Main\; \
    send-keys 'todo' c-m \; \
    split-window -h -p 30\; \
    clock-mode \; \
    split-window -v -p 75\; \
    send-keys 'python' c-m c-l\; \
    select-pane -t 0 \; \
    rename-window 'to-do' \; \
    new-window \; \
    rename-window 'Bash' \; \
    select-window -t 1 \;

