#!/usr/bin/env bash
session=$(echo $OP_SESSION_saed_family);

if [ "$session" = "" ]
then
    session=$(op signin saed_family --output=raw)
    export OP_SESSION_saed_family=$session
fi
   
op get item $1 | jq '.details.fields[] | select(.designation=="password").value' | sed s/\"//g | xclip -selection c
