#!/usr/bin/env  bash

brightnessFile="/sys/class/backlight/intel_backlight/brightness"

currentBrightnessValue=$(cat /sys/class/backlight/intel_backlight/brightness)
maximumBrightnessValue=$(cat /sys/class/backlight/intel_backlight/max_brightness)

stepValue=450

case ${1} in

    h)
        newBrightnessValue=$(( ${currentBrightnessValue} + ${stepValue} ))
        if [ ${newBrightnessValue} -le ${maximumBrightnessValue} ]; then
            echo -n ${newBrightnessValue} > ${brightnessFile}
        fi
        ;;

    l)
        newBrightnessValue=$(( ${currentBrightnessValue} - ${stepValue} ))
        if [ ${newBrightnessValue} -le 0 ]; then
            echo -n 0 > ${brightnessFile}
        else
            echo -n ${newBrightnessValue} > ${brightnessFile}
        fi
        ;;

    d) # default state
        echo -n ${stepValue} > ${brightnessFile}
        ;;

    b) # blank
        echo -n 0 > ${brightnessFile}
        ;;

    *)
        echo "Help:"
        echo -e "\tl for go lower"
        echo -e "\th for go higher"
        echo -e "\td for default state"
        echo -e "\tb for blank"
        echo
        ;;

esac
