#!/usr/bin/env bash

for fgbg in 38 48 ; do
    for color in {0..15}; do
        printf "\e[${fgbg};5;%sm  %3s  \e[0m" $color $color
        if [ $((($color + 1 ) % 4)) == 1 ]; then
            echo
        fi
    done
    echo
done

