#!/usr/bin/env bash

docker images | grep -v REPO | awk '{print $1}' | xargs -L1 docker pull 

# Remove images with none tag
imagesToRemove=$(docker images | grep \<none\> | awk '{print $3}')
echo $imagesToRemove 
if [ ! -z "$imagesToRemove" ];
then
    docker images | grep \<none\> | awk '{print $3}' | xargs -L1 docker rmi
fi
