#!/usr/bin/env bash

path1="${HOME}/Dropbox/screenshots/$(date +%Y-%m-%d-%H-%M-%S).png"
path2="${HOME}/Dropbox/Notes/img/$(date +%Y-%m-%d-%H-%M-%S).png"

case $1 in
    note)
        path=$path2
        ;;
    *)
        path=$path1
        ;;
esac

scrot -s $path
echo $path | xclip -selection c

