#!/usr/bin/env bash

output=$(date '+%Y-%m-%d-%H-%M-%S')

function getScreenSize() {
    size=$(xrandr | grep \* | awk {'print $1; exit'})
}

function screenCapture() {
    getScreenSize
    ffmpeg -f x11grab  -s $size -i :0.0 -r 25 -vcodec libx264  $output.mkv &> /dev/null
}

function screenCaptureWithAudio() {
    getScreenSize
    ffmpeg -f alsa -i hw:0 -f x11grab -s $size -i :0.0 -r 25 -vcodec libx264  $output.mkv &> /dev/null
}

function startWebcam() {
    ffplay -f video4linux2 -i /dev/video0 -video_size 320x240 &> /dev/null &
    sleep 2;
}

# Screen Capture
if [ "$#" -eq "0" ]; 
then
    ## Start screen capture
    screenCapture
fi

#Screen Capture with Audio
if [ "$1" == "-a" ];
then
    ## Start Screen Capture with audio
    screenCaptureWithAudio
fi

# Screen Capture with Webcam
if [ "$1" == "-w" ];
then
    ## Start Webcam
    startWebcam
    ## Start Screen Capture with audio
    screenCaptureWithAudio
fi

# Help
if [ "$1" == "-h" ];
then
    printf "\n$0 help\n\n"
    h="to show this help"
    printf "\t%s $h\n" -h
    a="Screen capture with audio"
    printf "\t%s $a\n" -a
    w="Screen capture with webcam"
    printf "\t%s $w\n" -w
fi

# Exit
if [ "$1" == "-q" ];
then
    sleep 2;
    pkill --signal SIGINT -g $(ps x -o "%r %c" | grep ffmpeg | awk {'print $1'}) -e
fi
