#!/usr/bin/env bash

mainScreen=$(xrandr | grep -w primary | awk '{print $1}')
SecondScreenIsConnected=$(xrandr | grep -w connected | grep -v primary | awk {'print $1'})
SecondScreenIsextended=$(xrandr | grep -w connected | grep -v primary | awk {'print $14'})

if [ "$1" == "off" ] && [ "${SecondScreenIsConnected}" ]; then
    xrandr --output ${SecondScreenIsConnected} --off --output ${mainScreen} --auto
elif [ "$1" == "off" ]; then
    xrandr --output ${mainScreen} --auto
elif [ "$1" == "m" ] && [ "${SecondScreenIsConnected}" ]; then
    xrandr --output ${mainScreen} --auto --output ${SecondScreenIsConnected} --auto --same-as ${mainScreen}
elif [ "$1" == "e" ] && [ "${SecondScreenIsConnected}" ] ; then
    xrandr --output  ${mainScreen} --auto --output ${SecondScreenIsConnected} --auto --above ${mainScreen}
elif [ "$1" == "s" ] && [ "${SecondScreenIsConnected}" ] ; then
    xrandr --output ${mainScreen} --off --output ${SecondScreenIsConnected} --auto
else 
    echo "No second screen is connected"
fi
