#!/usr/bin/env bash
currentTheme=$(cat ~/.Xresources | grep theme | cut -d' ' -f3)
theme=""

case $currentTheme in

    light)
        theme=dark
        ;;
    dark)
        theme=light
        ;;
esac

newcolor=""
oldcolor=""
for i in {0..9} {A..F}; do
    newcolor="${newcolor}\n$(cat ~/.colors/base16-solarized-${theme} | grep -w "#define base0${i}")"
    oldcolor="${oldcolor}\n$(cat ~/.Xresources | grep -w "#define base0${i}")"
done

sed "s/${currentTheme}/${theme}/" <~/.Xresources >~/.Xresources.tmp
sed ':a;N;$!ba;s/'"${oldcolor}"'/'"${newcolor}"'/' <~/.Xresources.tmp >~/.Xresources
rm .Xresources.tmp
xrdb -merge ~/.Xresources
hsetroot -solid "$(xrdb -query | grep -w color0 | cut -f2)"
killall st
i3-msg reload
exit 0
